"""Initial database schema

Revision ID: ba24561c4834
Revises: 
Create Date: 2026-06-29 23:32:26.106288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba24561c4834'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_processing_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_retries >= 0', name='ck_ai_jobs_max_retries_non_negative'),
    sa.CheckConstraint('priority BETWEEN 1 AND 10', name='ck_ai_jobs_priority_range'),
    sa.CheckConstraint('processing_time_ms IS NULL OR processing_time_ms >= 0', name='ck_ai_jobs_processing_time_non_negative'),
    sa.CheckConstraint('retry_count >= 0', name='ck_ai_jobs_retry_count_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    comment='Persistent async job queue for AI pipeline operations. Background workers poll this table for jobs to process.'
    )
    with op.batch_alter_table('ai_processing_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_ai_jobs_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_ai_jobs_job_type_status', ['job_type', 'status'], unique=False)
        batch_op.create_index('ix_ai_jobs_next_retry_at', ['next_retry_at'], unique=False, postgresql_where=sa.text("status = 'queued' AND next_retry_at IS NOT NULL"))
        batch_op.create_index('ix_ai_jobs_worker_pickup', ['status', 'priority', 'queued_at'], unique=False, postgresql_where=sa.text("status = 'queued'"))

    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='User role definitions. Seeded at database initialization. Never modified at runtime.'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_suspended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verification_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    comment='Core identity and authentication table. Role-specific profile data lives in candidate_profiles and recruiter_profiles.'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_users_is_active_suspended', ['is_active', 'is_suspended'], unique=False)
        batch_op.create_index('ix_users_role_id', ['role_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable audit log. Rows are never updated or deleted. Records every significant platform action for security and compliance.'
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_action_created_at', ['action', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_type_entity_id', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('availability', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('years_of_experience >= 0', name='ck_candidate_profiles_years_of_experience_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='Candidate-specific profile data. One-to-one extension of users for the candidate role. AI-extracted resume content is stored separately in resumes.parsed_data.'
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_profiles_availability', ['availability'], unique=False)
        batch_op.create_index('ix_candidate_profiles_location', ['location'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('template', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable email delivery audit trail. Updated by provider webhooks as delivery status changes.'
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index('ix_email_logs_provider_message_id', ['provider_message_id'], unique=False)
        batch_op.create_index('ix_email_logs_recipient_email', ['recipient_email'], unique=False)
        batch_op.create_index('ix_email_logs_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_email_logs_template', ['template'], unique=False)
        batch_op.create_index('ix_email_logs_user_id_created_at', ['user_id', 'created_at'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_remote', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('skills_required', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('nice_to_have_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jd_file_path', sa.String(length=500), nullable=True),
    sa.Column('views_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('applications_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('applications_count >= 0', name='ck_jobs_applications_count_non_negative'),
    sa.CheckConstraint('salary_max IS NULL OR salary_min IS NULL OR salary_max >= salary_min', name='ck_jobs_salary_max_gte_min'),
    sa.CheckConstraint('views_count >= 0', name='ck_jobs_views_count_non_negative'),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Job postings created by recruiters. The central entity for the AI candidate ranking pipeline.'
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_jobs_experience_level', ['experience_level'], unique=False)
        batch_op.create_index('ix_jobs_is_remote', ['is_remote'], unique=False)
        batch_op.create_index('ix_jobs_job_type', ['job_type'], unique=False)
        batch_op.create_index('ix_jobs_nice_to_have_skills_gin', ['nice_to_have_skills'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_jobs_recruiter_id', ['recruiter_id'], unique=False)
        batch_op.create_index('ix_jobs_skills_required_gin', ['skills_required'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_jobs_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='info', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='normal', nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='In-app notification feed. Soft-deletable (user dismissal). Polymorphic reference allows linking to any platform entity.'
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_notifications_reference', ['reference_type', 'reference_id'], unique=False)
        batch_op.create_index('ix_notifications_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_notifications_user_id_is_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index('ix_notifications_user_priority_read', ['user_id', 'priority', 'is_read'], unique=False)

    op.create_table('recruiter_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    comment='Recruiter and company profile data. One-to-one extension of users for the recruiter role.'
    )
    with op.batch_alter_table('recruiter_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_recruiter_profiles_company_name', ['company_name'], unique=False)
        batch_op.create_index('ix_recruiter_profiles_company_size', ['company_size'], unique=False)
        batch_op.create_index('ix_recruiter_profiles_industry', ['industry'], unique=False)

    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('previous_resume_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('parse_status', sa.String(length=30), server_default='uploaded', nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedding_stored', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quality_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_resumes_file_size_bytes_positive'),
    sa.CheckConstraint('quality_score IS NULL OR (quality_score >= 0 AND quality_score <= 100)', name='ck_resumes_quality_score_range'),
    sa.CheckConstraint('version >= 1', name='ck_resumes_version_at_least_one'),
    sa.ForeignKeyConstraint(['previous_resume_id'], ['resumes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Uploaded resume files and their AI-processing state. parsed_data, quality_report, and ai_metadata are JSONB — populated progressively as the AI pipeline processes the file.'
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index('ix_resumes_is_primary', ['is_primary'], unique=False)
        batch_op.create_index('ix_resumes_parse_status', ['parse_status'], unique=False)
        batch_op.create_index('ix_resumes_previous_resume_id', ['previous_resume_id'], unique=False)
        batch_op.create_index('ix_resumes_user_id', ['user_id'], unique=False)
        batch_op.create_index('uix_resumes_one_primary_per_active_user', ['user_id'], unique=True, postgresql_where=sa.text('is_primary = TRUE AND deleted_at IS NULL'))
        batch_op.create_index('uix_resumes_user_sha256', ['user_id', 'sha256_hash'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    comment='Runtime-configurable key-value settings. Admin-editable without code changes or redeployment.'
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('ix_system_settings_category', ['category'], unique=False)
        batch_op.create_index('ix_system_settings_is_public', ['is_public'], unique=False)

    op.create_table('token_blocklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti'),
    comment='Revoked JWT token IDs (JTIs). Checked on every authenticated request. Rows older than 30 days can be safely deleted by a cleanup job.'
    )
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.create_index('ix_token_blocklist_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_token_blocklist_user_id', ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='applied', nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ranking_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_gap', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interview_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_ai_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recruiter_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('match_score IS NULL OR (match_score >= 0 AND match_score <= 100)', name='ck_applications_match_score_range'),
    sa.CheckConstraint('rank IS NULL OR rank >= 1', name='ck_applications_rank_positive'),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_applications_job_candidate'),
    comment='Candidate applications. Connects a candidate, a job, and a resume. Stores the complete AI scoring and application lifecycle.'
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index('ix_applications_candidate_created', ['candidate_id', 'created_at'], unique=False)
        batch_op.create_index('ix_applications_job_score', ['job_id', 'match_score'], unique=False)
        batch_op.create_index('ix_applications_job_status', ['job_id', 'status'], unique=False)
        batch_op.create_index('ix_applications_last_ai_processed_at', ['last_ai_processed_at'], unique=False)
        batch_op.create_index('ix_applications_resume_id', ['resume_id'], unique=False)
        batch_op.create_index('ix_applications_status_updated_at', ['status_updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index('ix_applications_status_updated_at')
        batch_op.drop_index('ix_applications_resume_id')
        batch_op.drop_index('ix_applications_last_ai_processed_at')
        batch_op.drop_index('ix_applications_job_status')
        batch_op.drop_index('ix_applications_job_score')
        batch_op.drop_index('ix_applications_candidate_created')

    op.drop_table('applications')
    with op.batch_alter_table('token_blocklist', schema=None) as batch_op:
        batch_op.drop_index('ix_token_blocklist_user_id')
        batch_op.drop_index('ix_token_blocklist_created_at')

    op.drop_table('token_blocklist')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_system_settings_is_public')
        batch_op.drop_index('ix_system_settings_category')

    op.drop_table('system_settings')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index('uix_resumes_user_sha256')
        batch_op.drop_index('uix_resumes_one_primary_per_active_user', postgresql_where=sa.text('is_primary = TRUE AND deleted_at IS NULL'))
        batch_op.drop_index('ix_resumes_user_id')
        batch_op.drop_index('ix_resumes_previous_resume_id')
        batch_op.drop_index('ix_resumes_parse_status')
        batch_op.drop_index('ix_resumes_is_primary')
        batch_op.drop_index(batch_op.f('ix_resumes_deleted_at'))

    op.drop_table('resumes')
    with op.batch_alter_table('recruiter_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_recruiter_profiles_industry')
        batch_op.drop_index('ix_recruiter_profiles_company_size')
        batch_op.drop_index('ix_recruiter_profiles_company_name')

    op.drop_table('recruiter_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_priority_read')
        batch_op.drop_index('ix_notifications_user_id_is_read')
        batch_op.drop_index('ix_notifications_user_id_created_at')
        batch_op.drop_index('ix_notifications_reference')
        batch_op.drop_index(batch_op.f('ix_notifications_deleted_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status_created_at')
        batch_op.drop_index('ix_jobs_skills_required_gin', postgresql_using='gin')
        batch_op.drop_index('ix_jobs_recruiter_id')
        batch_op.drop_index('ix_jobs_nice_to_have_skills_gin', postgresql_using='gin')
        batch_op.drop_index('ix_jobs_job_type')
        batch_op.drop_index('ix_jobs_is_remote')
        batch_op.drop_index('ix_jobs_experience_level')
        batch_op.drop_index(batch_op.f('ix_jobs_deleted_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_email_logs_user_id_created_at')
        batch_op.drop_index('ix_email_logs_template')
        batch_op.drop_index('ix_email_logs_status_created_at')
        batch_op.drop_index('ix_email_logs_recipient_email')
        batch_op.drop_index('ix_email_logs_provider_message_id')

    op.drop_table('email_logs')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_profiles_location')
        batch_op.drop_index('ix_candidate_profiles_availability')

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_user_id_created_at')
        batch_op.drop_index('ix_audit_logs_entity_type_entity_id')
        batch_op.drop_index('ix_audit_logs_created_at')
        batch_op.drop_index('ix_audit_logs_action_created_at')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_id')
        batch_op.drop_index('ix_users_is_active_suspended')
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('ai_processing_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_jobs_worker_pickup', postgresql_where=sa.text("status = 'queued'"))
        batch_op.drop_index('ix_ai_jobs_next_retry_at', postgresql_where=sa.text("status = 'queued' AND next_retry_at IS NOT NULL"))
        batch_op.drop_index('ix_ai_jobs_job_type_status')
        batch_op.drop_index('ix_ai_jobs_entity_type_entity_id')

    op.drop_table('ai_processing_jobs')
    # ### end Alembic commands ###
